apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dapr.io/app-id: dapr-articles
    dapr.io/app-port: "80"
    dapr.io/enabled: "true"
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"dapr.io/app-id":"dapr-articles","dapr.io/app-port":"80","dapr.io/enabled":"true"},"labels":{"app.kubernetes.io/name":"dapr-articles","app.kubernetes.io/part-of":"dapr"},"name":"dapr-articles","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/name":"dapr-articles"}},"template":{"metadata":{"annotations":{"dapr.io/app-id":"dapr-articles","dapr.io/app-port":"80","dapr.io/enabled":"true"},"labels":{"app.kubernetes.io/name":"dapr-articles","app.kubernetes.io/part-of":"dapr"}},"spec":{"containers":[{"env":[{"name":"DOTNET_LOGGING__CONSOLE__DISABLECOLORS","value":"true"},{"name":"ASPNETCORE_URLS","value":"http://*"},{"name":"PORT","value":"80"},{"name":"SERVICE__DAPR-ARTICLES__PROTOCOL","value":"http"},{"name":"SERVICE__DAPR-ARTICLES__PORT","value":"80"},{"name":"SERVICE__DAPR-ARTICLES__HOST","value":"dapr-articles"},{"name":"SERVICE__DAPR-SHOPINGCART__PROTOCOL","value":"http"},{"name":"SERVICE__DAPR-SHOPINGCART__PORT","value":"80"},{"name":"SERVICE__DAPR-SHOPINGCART__HOST","value":"dapr-shopingcart"},{"name":"SERVICE__DAPR-FINANCIAL__PROTOCOL","value":"http"},{"name":"SERVICE__DAPR-FINANCIAL__PORT","value":"80"},{"name":"SERVICE__DAPR-FINANCIAL__HOST","value":"dapr-financial"},{"name":"SERVICE__DAPR-INVENTORY__PROTOCOL","value":"http"},{"name":"SERVICE__DAPR-INVENTORY__PORT","value":"80"},{"name":"SERVICE__DAPR-INVENTORY__HOST","value":"dapr-inventory"}],"image":"containerregistrygeorgepatrascudaprdemo.azurecr.io/dapr-articles:1.0.0","imagePullPolicy":"Always","name":"dapr-articles","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2022-09-11T14:01:05Z"
  generation: 3
  labels:
    app.kubernetes.io/name: dapr-articles
    app.kubernetes.io/part-of: dapr
  name: dapr-articles
  namespace: default
  resourceVersion: "436690"
  uid: 64ef0c09-37dc-478f-8bc9-cba792c0db7a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: dapr-articles
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: dapr-articles
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        dapr.io/config: appconfig
        kubectl.kubernetes.io/restartedAt: "2022-09-11T17:40:23Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: dapr-articles
        app.kubernetes.io/part-of: dapr
    spec:
      containers:
      - env:
        - name: DOTNET_LOGGING__CONSOLE__DISABLECOLORS
          value: "true"
        - name: ASPNETCORE_URLS
          value: http://*
        - name: PORT
          value: "80"
        - name: SERVICE__DAPR-ARTICLES__PROTOCOL
          value: http
        - name: SERVICE__DAPR-ARTICLES__PORT
          value: "80"
        - name: SERVICE__DAPR-ARTICLES__HOST
          value: dapr-articles
        - name: SERVICE__DAPR-SHOPINGCART__PROTOCOL
          value: http
        - name: SERVICE__DAPR-SHOPINGCART__PORT
          value: "80"
        - name: SERVICE__DAPR-SHOPINGCART__HOST
          value: dapr-shopingcart
        - name: SERVICE__DAPR-FINANCIAL__PROTOCOL
          value: http
        - name: SERVICE__DAPR-FINANCIAL__PORT
          value: "80"
        - name: SERVICE__DAPR-FINANCIAL__HOST
          value: dapr-financial
        - name: SERVICE__DAPR-INVENTORY__PROTOCOL
          value: http
        - name: SERVICE__DAPR-INVENTORY__PORT
          value: "80"
        - name: SERVICE__DAPR-INVENTORY__HOST
          value: dapr-inventory
        image: containerregistrygeorgepatrascudaprdemo.azurecr.io/dapr-articles:1.0.0
        imagePullPolicy: Always
        name: dapr-articles
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-09-11T14:01:24Z"
    lastUpdateTime: "2022-09-11T14:01:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-09-11T14:01:05Z"
    lastUpdateTime: "2022-09-11T17:40:30Z"
    message: ReplicaSet "dapr-articles-7fc7b77554" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
